[versions]
agp = "8.9.1"
kotlin = "2.1.0"

[libraries]
# (add libs here later as needed)

[plugins]
android-app = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
