name: Android CI
on:
  push:
    branches: ["**"]
  pull_request:
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"
      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-36" "build-tools;35.0.0"
      - name: Use JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Pub
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      - name: Check required Firebase secrets
        env:
          ANDROID_JSON: ${{ secrets.ANDROID_GOOGLE_SERVICES_JSON }}
          IOS_PLIST_B64: ${{ secrets.IOS_GOOGLE_SERVICE_INFO_PLIST }}
        run: |
          if [ -z "$ANDROID_JSON" ]; then
            echo "::error::Missing ANDROID_GOOGLE_SERVICES_JSON (base64 of android/app/google-services.json)"
            exit 1
          fi
          echo "::notice::ANDROID_GOOGLE_SERVICES_JSON present."
          if [ -z "$IOS_PLIST_B64" ]; then
            echo "::warning::IOS_GOOGLE_SERVICE_INFO_PLIST not set. iOS config will be skipped."
          fi

      - name: Write google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.ANDROID_GOOGLE_SERVICES_JSON }}
        run: |
          # Mask the secret so it won't show in logs
          echo "::add-mask::$GOOGLE_SERVICES_JSON"
          mkdir -p android/app
          echo "$GOOGLE_SERVICES_JSON" | base64 --decode > android/app/google-services.json
          test -s android/app/google-services.json

      - name: Write GoogleService-Info.plist (optional)
        if: ${{ secrets.IOS_GOOGLE_SERVICE_INFO_PLIST != '' }}
        env:
          IOS_PLIST: ${{ secrets.IOS_GOOGLE_SERVICE_INFO_PLIST }}
        run: |
          # Mask the secret so it won't show in logs
          echo "::add-mask::$IOS_PLIST"
          mkdir -p ios/Runner
          echo "$IOS_PLIST" | base64 --decode > ios/Runner/GoogleService-Info.plist
          test -s ios/Runner/GoogleService-Info.plist

      - name: Gradle setup & caching
        uses: gradle/actions/setup-gradle@v3
      - name: Flutter pub get
        run: flutter pub get
      - name: Build APK (debug)
        run: flutter build apk --debug
